// src/components/AudioPlayer.jsx
import React from 'react'
import { useAudiobooks } from '../contexts/AudiobooksContext'
import { Play, Pause, SkipBack, SkipForward, X, Volume2 } from 'lucide-react'

const AudioPlayer = () => {
  const {
    currentBook,
    isPlaying,
    currentTime,
    duration,
    volume,
    pauseBook,
    resumeBook,
    seekTo,
    setVolume,
    stopBook
  } = useAudiobooks()

  if (!currentBook) return null

  const formatTime = (seconds) => {
    const hours = Math.floor(seconds / 3600)
    const minutes = Math.floor((seconds % 3600) / 60)
    const secs = Math.floor(seconds % 60)
    
    if (hours > 0) {
      return `${hours}:${minutes.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`
    }
    return `${minutes}:${secs.toString().padStart(2, '0')}`
  }

  const handleSeek = (e) => {
    const rect = e.currentTarget.getBoundingClientRect()
    const percent = (e.clientX - rect.left) / rect.width
    const newTime = percent * duration
    seekTo(newTime)
  }

  const skipBackward = () => {
    const newTime = Math.max(0, currentTime - 15)
    seekTo(newTime)
  }

  const skipForward = () => {
    const newTime = Math.min(duration, currentTime + 15)
    seekTo(newTime)
  }

  return (
    <div className="p-4">
      <div className="flex items-center space-x-4">
        {/* Book Cover */}
        <img
          src={currentBook.cover}
          alt={currentBook.title}
          className="w-12 h-12 rounded-lg object-cover"
        />

        {/* Book Info */}
        <div className="flex-1 min-w-0">
          <div className="text-sm font-medium truncate">{currentBook.title}</div>
          <div className="text-xs text-gray-400 truncate">{currentBook.author}</div>
        </div>

        {/* Controls */}
        <div className="flex items-center space-x-2">
          <button
            onClick={skipBackward}
            className="p-1 rounded-full hover:bg-gray-700 transition-colors"
          >
            <SkipBack className="w-4 h-4" />
          </button>
          
          <button
            onClick={isPlaying ? pauseBook : resumeBook}
            className="p-2 rounded-full bg-primary-600 hover:bg-primary-700 transition-colors"
          >
            {isPlaying ? <Pause className="w-4 h-4" /> : <Play className="w-4 h-4" />}
          </button>
          
          <button
            onClick={skipForward}
            className="p-1 rounded-full hover:bg-gray-700 transition-colors"
          >
            <SkipForward className="w-4 h-4" />
          </button>

          <button
            onClick={stopBook}
            className="p-1 rounded-full hover:bg-gray-700 transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* Progress Bar */}
      <div className="mt-3">
        <div
          className="w-full h-1 bg-gray-600 rounded-full cursor-pointer"
          onClick={handleSeek}
        >
          <div
            className="h-full bg-primary-600 rounded-full transition-all"
            style={{ width: `${(currentTime / duration) * 100}%` }}
          />
        </div>
        <div className="flex justify-between text-xs text-gray-400 mt-1">
          <span>{formatTime(currentTime)}</span>
          <span>{formatTime(duration)}</span>
        </div>
      </div>
    </div>
  )
}

export default AudioPlayer

// src/components/AudioPlayer.vue
<template>
  <div class="audio-player q-pa-md">
    <div class="row items-center q-gutter-md">
      <!-- Book Cover -->
      <q-avatar size="50px" rounded>
        <img :src="currentBook.cover" :alt="currentBook.title" />
      </q-avatar>

      <!-- Book Info -->
      <div class="col">
        <div class="text-subtitle2 text-weight-medium ellipsis">
          {{ currentBook.title }}
        </div>
        <div class="text-caption text-grey-5 ellipsis">
          {{ currentBook.author }}
        </div>
      </div>

      <!-- Controls -->
      <div class="row items-center q-gutter-sm">
        <q-btn
          flat
          dense
          round
          icon="skip_previous"
          size="sm"
          @click="skipBackward"
        />
        
        <q-btn
          flat
          dense
          round
          :icon="isPlaying ? 'pause' : 'play_arrow'"
          size="md"
          @click="togglePlay"
        />
        
        <q-btn
          flat
          dense
          round
          icon="skip_next"
          size="sm"
          @click="skipForward"
        />

        <q-btn
          flat
          dense
          round
          icon="close"
          size="sm"
          @click="closePlayer"
        />
      </div>
    </div>

    <!-- Progress Bar -->
    <div class="q-mt-sm">
      <q-slider
        v-model="currentTime"
        :min="0"
        :max="duration || 100"
        :step="1"
        color="primary"
        track-color="grey-7"
        @change="seekTo"
      />
      <div class="row justify-between text-caption text-grey-5">
        <span>{{ formatTime(currentTime) }}</span>
        <span>{{ formatTime(duration) }}</span>
      </div>
    </div>

    <!-- Volume Control (expandable) -->
    <q-expansion-item
      v-if="showVolumeControl"
      icon="volume_up"
      label="Volume"
      dense
    >
      <q-slider
        v-model="volume"
        :min="0"
        :max="1"
        :step="0.1"
        color="primary"
        @change="setVolume"
      />
    </q-expansion-item>
  </div>
</template>

<script setup>
import { computed, ref } from 'vue'
import { useAudiobooksStore } from 'src/stores/audiobooks'

const audiobooksStore = useAudiobooksStore()
const showVolumeControl = ref(false)

const currentBook = computed(() => audiobooksStore.currentBook)
const isPlaying = computed(() => audiobooksStore.isPlaying)
const currentTime = computed({
  get: () => audiobooksStore.currentTime,
  set: (value) => audiobooksStore.currentTime = value
})
const duration = computed(() => audiobooksStore.duration || 100)
const volume = computed({
  get: () => audiobooksStore.volume,
  set: (value) => audiobooksStore.volume = value
})

const togglePlay = () => {
  if (isPlaying.value) {
    audiobooksStore.pauseBook()
  } else {
    audiobooksStore.resumeBook()
  }
}

const skipBackward = () => {
  const newTime = Math.max(0, currentTime.value - 15)
  audiobooksStore.seekTo(newTime)
}

const skipForward = () => {
  const newTime = Math.min(duration.value, currentTime.value + 15)
  audiobooksStore.seekTo(newTime)
}

const seekTo = (time) => {
  audiobooksStore.seekTo(time)
}

const setVolume = (vol) => {
  audiobooksStore.setVolume(vol)
}

const closePlayer = () => {
  audiobooksStore.stopBook()
}

const formatTime = (seconds) => {
  const hours = Math.floor(seconds / 3600)
  const minutes = Math.floor((seconds % 3600) / 60)
  const secs = Math.floor(seconds % 60)
  
  if (hours > 0) {
    return `${hours}:${minutes.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`
  }
  return `${minutes}:${secs.toString().padStart(2, '0')}`
}
</script>

<style scoped>
.audio-player {
  background: linear-gradient(135deg, #1a1a1a 0%, #2d2d2d 100%);
  border-top: 1px solid #333;
}
</style>
